name: Cancel Workflow on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  cancel_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is closed
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONALAT }}
          script: |
            const prState = context.payload.pull_request.state;
            if (prState === 'closed') {
              console.log('PR is closed');
              // Use GitHub REST API to cancel workflow run associated with this PR
              const response = await octokit.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: github.run_id
              });
              console.log(response.data);
            } else {
              console.log('PR is not closed');
            }

# Credit to https://stackoverflow.com/a/76318991/22527164
